baseURL = "https://example.com/"
languageCode = "en-US"
title = "Byte-Size ML: Steven Lasch personal website and blog"
theme = "personal-site"
summaryLength = 10

[Author]
avatar = "https://avatars.githubusercontent.com/u/91107394?v=4"
bio = "Data scientist with experience in data processing, data visualization, and machine learning. Dedicated to utilizing programming and analytical skills to create data-driven products."
donate = false
email = "slasch44@lakers.mercyhurst.edu"
gender = "male"
job = "Data Scientist"
name = "Steven Lasch"

[Params]
GoogleAnalytics = ""
authorbox = true
comments = true
copyright = "Steven Lasch"
customJS = []
customSearchId = ""
dateFormat = "January 02, 2006"
description = "Data scientist with experience in data processing, data visualization, and machine learning. Dedicated to utilizing programming and analytical skills to create data-driven products."
editContentPageLink = "https://github.com/s-lasch/personal-site/tree/master/content/"
endMessagePost = "If you see any errors, typos, or bug fixes, feel free to leave a comment, or contribute directly on my GitHub."
fb_admins = ""
fb_app_id = ""
fontUnit = "em"
formspreeId = "mvojardv"
googleSearchConsole = ""
hideNoPostsWarning = false
images = ["https://avatars.githubusercontent.com/u/91107394?v=4"]
largestFontSize = 2.5
mainMenuAlignment = "center"
mainSections = ["post", "snippet"]
mathjax = true
opengraph = true
paginateLength = 5
related = true
relatedMax = 5
smallestFontSize = 1
subTitle = "Personal site, Blog, and Portfolio"
twitter_cards = true

[Params.Breadcrumb]
enable = true
homeText = "Home"

[Params.Comments]
repository = "s-lasch/personal-site"

[Params.Entry]
meta = ["date"]
toc = true

[Params.Hero]
title = "Hello! I'm Steven Lasch."
desc = "A data-driven professional."

[Params.Manifest]
backgroundColor = "#8dc153"
description = "Personal Site by Steven Lasch"
display = "standalone"
name = "Byte-Size ML"
orientation = "portrait"
scope = "/"
shortName = "SL-ML"
startUrl = "/?utm_source=homescreen"
themeColor = "#1da1f2"

[Params.Share]
medium = true
linkedin = true

[Params.Social]
github = "s-lasch/personal-site"
# gitlab = "jhondoe"
linkedin = "steven-l-lasch"
medium = "stevenlasch17"
telegram = "stevenlasch"
# twitter = "jhondoe"
[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = false
style = "dracula"
tabWidth = 4

[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 2

[[menu.main]]
identifier = "Contact"
pre = ""
url = "/contact"
weight = 5
[[menu.main]]
identifier = "Presentations"
pre = ""
url = "/presentations"
weight = 4
[[menu.main]]
identifier = "Resume"
pre = ""
url = "/resume"
weight = 3
[[menu.main]]
identifier = "About"
pre = ""
url = "/about"
weight = 2
# [[menu.main]]
# identifier = "Snippet"
# pre = ""
# url = "/snippet"
# weight = 3
[[menu.main]]
identifier = "Posts"
pre = ""
url = "/post"
weight = 1
# [[menu.main]]
# identifier = "Series"
# pre = ""
# url = "/series"
# weight = 1

[outputFormats.MANIFEST]
baseName = "manifest"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[outputs]
Paginate = 5
enableRobotsTXT = true
home = ["HTML", "RSS", "MANIFEST"]

[sitemap]
changeFreqPage = "monthly"
changefreq = "daily"
filename = "sitemap.xml"
priority = 1
priorityPage = 0.5

[markup.goldmark.renderer]
unsafe= true
